# NUMPY

In [1]:
import numpy
numpy.__version__

'1.15.4'

In [2]:
import pandas
pandas.__version__

'0.23.4'

In [3]:
import matplotlib
matplotlib.__version__

'2.2.3'

In [4]:
numpy.array([23,67,89])

array([23, 67, 89])

In [6]:
print(numpy.array([23,67,89]))
print([23,67,89])

[23 67 89]
[23, 67, 89]


In [7]:
import numpy as np

In [8]:
a = np.array([78,89,90])
a

array([78, 89, 90])

In [9]:
# Create an array with tuple
a1 = np.array((67,78,89))
a1

array([67, 78, 89])

In [10]:
a2 = np.array(range(5,20,2))
a2

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
a3 = np.arange(5,20,2)
a3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
type(a),type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
a4 = np.arange(5,10,2.5)
a4

array([5. , 7.5])

In [14]:
a5 = np.linspace(4,78,8)
a5

array([ 4.        , 14.57142857, 25.14285714, 35.71428571, 46.28571429,
       56.85714286, 67.42857143, 78.        ])

In [15]:
a6 = np.linspace(1,10,10)
a6

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
a7 = np.array([[1,2],[3,4]])
a7

array([[1, 2],
       [3, 4]])

In [25]:
a8 = np.random.rand(3,5)
a8

array([[0.36156829, 0.68314385, 0.34786665, 0.94282022, 0.51930049],
       [0.98154649, 0.19466541, 0.56559458, 0.89560037, 0.91683075],
       [0.36914625, 0.16446894, 0.80587139, 0.9659583 , 0.78667253]])

In [28]:
a9 = np.random.random((3,5))
a9

array([[0.24150033, 0.94000702, 0.52738398, 0.62441564, 0.53502873],
       [0.30687225, 0.38263426, 0.35252049, 0.78853575, 0.32537133],
       [0.96837434, 0.62874173, 0.84465663, 0.60203363, 0.03184929]])

Normal Distribution

In [29]:
a10 = np.random.randn(5)
a10

array([-0.58628828,  0.06569084,  0.61973562,  1.02617804,  0.82000984])

Random integer generation<br>
np.random.randint(low,high,shape)

In [30]:
np.random.randint(4,10,4)

array([7, 7, 4, 6])

In [34]:
a11 = np.random.randint(5,100,(4,4))
a11

array([[47, 34, 21, 58],
       [42, 79, 74, 86],
       [83, 49, 32, 89],
       [17, 28, 87, 81]])

Slicing,Subsetting and Indexing<br>
**For 1d Array**
- arr[i] i is index of an elemnt<br>
- arr[i:] from index i to the end<br>
- arr[i:j] from index i to j-1<br>
- arr[i:j:s] from index i to j-1 with step s<br>
- arr[[1,4,5]] returns array with indices 1,4,5<br>

In [45]:
print(a1[0])
print(a5[0])
print(a5[3:])
print(a5[3:7])
print(a5[3:8:2])
print(a5[[1,6,5]]) # mention the indices as a list
print(a5)

67
4.0
[35.71428571 46.28571429 56.85714286 67.42857143 78.        ]
[35.71428571 46.28571429 56.85714286 67.42857143]
[35.71428571 56.85714286 78.        ]
[14.57142857 67.42857143 56.85714286]
[ 4.         14.57142857 25.14285714 35.71428571 46.28571429 56.85714286
 67.42857143 78.        ]


In [47]:
print(a11)

[[47 34 21 58]
 [42 79 74 86]
 [83 49 32 89]
 [17 28 87 81]]


In [50]:
print(a11[0])
print('-------------')
print(a11[1:4])
print('-------------')
print(a11[2:])

[47 34 21 58]
-------------
[[42 79 74 86]
 [83 49 32 89]
 [17 28 87 81]]
-------------
[[83 49 32 89]
 [17 28 87 81]]


In [61]:
#3rd row 4th element
print(a11[2][3])
print(a11[2:][1])
print(a11[1][3])

89
[17 28 87 81]
86


In [59]:
print(a11[[1,2,3],[3,1,0]]) #[(1,3)(2,1)(3,0)]

[86 49 17]


### Fancy Indexing or Boolean array as index

In [62]:
print(a1)

[67 78 89]


In [63]:
a1[[True,False,True]]

array([67, 89])

In [64]:
a11 > 50

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [65]:
a11[a11>50]

array([58, 79, 74, 86, 83, 89, 87, 81])

### Properties of an array

In [67]:
print(a11.dtype) # datatype
print(a11.size)  # no of elements
print(a11.ndim) # dimensions
print(a11.itemsize) # each itemsize in bytes
print(a11.shape) # Shape of the array as a tuple
print(a11.shape[0])

int32
16
2
4
(4, 4)
4


### Basic Math operations

In [69]:
print(a1,a)

[67 78 89] [78 89 90]


In [70]:
a1 + a

array([145, 167, 179])

In [71]:
a12 = np.array([1,1,1])
a12

array([1, 1, 1])

In [72]:
a1+a12

array([68, 79, 90])

In [73]:
a1 * a12

array([67, 78, 89])

In [75]:
a1 - a12

array([66, 77, 88])

### Broadcasting
Two rules
- in that dimension same value
- value is one<br>
Example<br>
(1,5) (5,5)<br>
(2,3,1)(1,3,5)<br>

In [76]:
a1 * 5

array([335, 390, 445])

In [77]:
a1 + a2

ValueError: operands could not be broadcast together with shapes (3,) (8,) 

In [82]:
b1 = np.random.randint(1,100,(2,3,2))
b2 =  np.random.randint(1,100,(2,1,2))
print(b1)
print('--------')
print(b2)
print('--------')
print(b1+b2)

[[[68  1]
  [ 9 59]
  [97 63]]

 [[35 76]
  [33 37]
  [18 85]]]
--------
[[[69 48]]

 [[ 6 17]]]
--------
[[[137  49]
  [ 78 107]
  [166 111]]

 [[ 41  93]
  [ 39  54]
  [ 24 102]]]


In [83]:
b1

array([[[68,  1],
        [ 9, 59],
        [97, 63]],

       [[35, 76],
        [33, 37],
        [18, 85]]])

In [84]:
import math
math.log(5)

1.6094379124341003

In [85]:
math.log(b1)

TypeError: only size-1 arrays can be converted to Python scalars

In [86]:
np.log(b1)

array([[[4.21950771, 0.        ],
        [2.19722458, 4.07753744],
        [4.57471098, 4.14313473]],

       [[3.55534806, 4.33073334],
        [3.49650756, 3.61091791],
        [2.89037176, 4.44265126]]])

In [87]:
np.add(a,a1)

array([145, 167, 179])

In [88]:
a+a1

array([145, 167, 179])

### Vectorized Function creation

In [89]:
def nmin(a,b):
    if a<b:
        return a
    else:
        return b

In [90]:
nmin(4,89)

4

In [91]:
anmin = np.vectorize(nmin)
anmin(a,a1)

array([67, 78, 89])

In [92]:
print(a,a1)

[78 89 90] [67 78 89]


### Array Manipulation

In [94]:
a11

array([[47, 34, 21, 58],
       [42, 79, 74, 86],
       [83, 49, 32, 89],
       [17, 28, 87, 81]])

In [95]:
a11.reshape(8,2)

array([[47, 34],
       [21, 58],
       [42, 79],
       [74, 86],
       [83, 49],
       [32, 89],
       [17, 28],
       [87, 81]])

In [96]:
a11.reshape(4,2,2)

array([[[47, 34],
        [21, 58]],

       [[42, 79],
        [74, 86]],

       [[83, 49],
        [32, 89]],

       [[17, 28],
        [87, 81]]])

In [97]:
a11.reshape(2,-1)

array([[47, 34, 21, 58, 42, 79, 74, 86],
       [83, 49, 32, 89, 17, 28, 87, 81]])

In [98]:
a11.reshape(-1)

array([47, 34, 21, 58, 42, 79, 74, 86, 83, 49, 32, 89, 17, 28, 87, 81])

In [99]:
a11.reshape(16)

array([47, 34, 21, 58, 42, 79, 74, 86, 83, 49, 32, 89, 17, 28, 87, 81])

In [101]:
a11.reshape(16,-1)

array([[47],
       [34],
       [21],
       [58],
       [42],
       [79],
       [74],
       [86],
       [83],
       [49],
       [32],
       [89],
       [17],
       [28],
       [87],
       [81]])

In [102]:
a11.reshape(16,1)

array([[47],
       [34],
       [21],
       [58],
       [42],
       [79],
       [74],
       [86],
       [83],
       [49],
       [32],
       [89],
       [17],
       [28],
       [87],
       [81]])

In [100]:
a11.flatten()

array([47, 34, 21, 58, 42, 79, 74, 86, 83, 49, 32, 89, 17, 28, 87, 81])

In [103]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [109]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
np.ones((6,2),dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [108]:
np.ones((6,2),dtype=bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [105]:
np.full((8,9),5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [110]:
a11

array([[47, 34, 21, 58],
       [42, 79, 74, 86],
       [83, 49, 32, 89],
       [17, 28, 87, 81]])

In [111]:
a11[0] =6

In [112]:
a11

array([[ 6,  6,  6,  6],
       [42, 79, 74, 86],
       [83, 49, 32, 89],
       [17, 28, 87, 81]])

### Stacking

In [113]:
print(a,a1)

[78 89 90] [67 78 89]


In [116]:
np.vstack([a,a1])

array([[78, 89, 90],
       [67, 78, 89]])

In [117]:
np.hstack([a,a1])

array([78, 89, 90, 67, 78, 89])

In [119]:
v1 = a.reshape(3,-1)
v2 = a1.reshape(3,-1)
print(v1)
print(v2)

[[78]
 [89]
 [90]]
[[67]
 [78]
 [89]]


In [121]:
np.hstack([v1,v2])

array([[78, 67],
       [89, 78],
       [90, 89]])

### Numpy as building block

In [123]:
import matplotlib.pyplot as plt
img = plt.imread("ml.png")
type(img)

numpy.ndarray

In [124]:
img.shape

(205, 245, 3)

In [128]:
img[0,0,:3]

array([1., 1., 1.], dtype=float32)

In [129]:
import sklearn.datasets

In [130]:
from sklearn.datasets import load_iris
data = load_iris()

In [131]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [132]:
print(data['DESCR'])

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [133]:
type(data['data'])

numpy.ndarray

In [134]:
data['data'].shape

(150, 4)

In [135]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# PANDAS

Topics
- Series -->1d Array
- DataFrame --> 2d Array
- Panel --> 3d Array

In [136]:
import pandas as pd
pd.Series([12,45,78,34])

0    12
1    45
2    78
3    34
dtype: int64

In [138]:
s = pd.Series([12,45,78,34],['one',
                'two','three','four'])
print(s)

one      12
two      45
three    78
four     34
dtype: int64


In [139]:
print(s[0],s['one'])

12 12


In [140]:
s1 = pd.Series((3,4,5,6))
s1

0    3
1    4
2    5
3    6
dtype: int64

In [141]:
s1.index = ['a','b','c','d']
s1

a    3
b    4
c    5
d    6
dtype: int64

In [142]:
d = {'python':9,'R':8,'Go':8,'PHP':5}
pd.Series(d)

python    9
R         8
Go        8
PHP       5
dtype: int64

In [143]:
temp = pd.Series([34,32,33,30,29.5])
temp

0    34.0
1    32.0
2    33.0
3    30.0
4    29.5
dtype: float64

In [144]:
pd.date_range("2019-10-15","2019-10-19")

DatetimeIndex(['2019-10-15', '2019-10-16', '2019-10-17', '2019-10-18',
               '2019-10-19'],
              dtype='datetime64[ns]', freq='D')

In [146]:
temp.index = pd.date_range("2019-10-15",
                           periods = 5)
temp

2019-10-15    34.0
2019-10-16    32.0
2019-10-17    33.0
2019-10-18    30.0
2019-10-19    29.5
Freq: D, dtype: float64

DataFrame

In [150]:
d1 = {'name':['hari','raju','giri','Raj'],
     'marks':[78,55,67,44],
     'attendance':[80,55,92,70]}
df = pd.DataFrame(d1)
df

name  marks  attendance
0  hari     78          80
1  raju     55          55
2  giri     67          92
3   Raj     44          70

In [154]:
a = np.array([['hari',78,80],
             ['raju',55,55],
             ['giri',67,92],
             ['Raj',44,70]])
df1 = pd.DataFrame(a,columns=['name',
            'marks','attendance'])
df1

name marks attendance
0  hari    78         80
1  raju    55         55
2  giri    67         92
3   Raj    44         70

In [155]:
df2 = pd.DataFrame(a,index = [416,434,422,411],
        columns=['name','marks','attendance'])
df2

name marks attendance
416  hari    78         80
434  raju    55         55
422  giri    67         92
411   Raj    44         70

In [156]:
df2['name']

416    hari
434    raju
422    giri
411     Raj
Name: name, dtype: object

In [159]:
df2[['name']]

name
416  hari
434  raju
422  giri
411   Raj

In [158]:
df2[['name','marks']]

name marks
416  hari    78
434  raju    55
422  giri    67
411   Raj    44

In [157]:
df2.columns

Index(['name', 'marks', 'attendance'], dtype='object')

In [166]:
marks_df = pd.read_csv("marks.csv",header=None,
        names=['name', 'marks', 'attendance'])
marks_df

name  marks  attendance
0  hari     78          80
1  raju     55          55
2  giri     67          92
3   Raj     44          70

In [168]:
marks_df = pd.read_csv("marks.csv",header=None,
        usecols=['name', 'attendance'],
    names=['name', 'marks', 'attendance']  )
marks_df

name  attendance
0  hari          80
1  raju          55
2  giri          92
3   Raj          70

In [164]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read CSV (comma-separated) file into DataFrame
    
    Also supports optionally itera

In [172]:
marks_df1 = pd.read_csv('marks.tsv',sep='\t')
marks_df1

Name  Marks  Attendance
0  hari     78          80
1  raju     55          55
2  giri     67          92
3   Raj     44          70

In [173]:
marks_df1.shape

(4, 3)