Topics
- Titanic Survival Data
- categorical Data
    - Lable Binarizer
    - Lable Encoder
    - One hot encoder(pd.getdummies())
- Scaling
- Choose the metric
- Apply 3 ML Algorithms
- Choose the best
- Parameters of the model
- parameter Tuning    
    - Gridserach
    - Random Serach

In [3]:
%matplotlib inline
# Data Analysis
import pandas as pd
import numpy as np
#Plotting
import matplotlib.pyplot as plt
import seaborn as sns
# Machine Learning Models
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
# Metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score


Read the data Display first 5 rows

In [4]:
df = pd.read_csv('Datasets/titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Check the missing values

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

There are three columns which have missing values<br>
Remove the Cabin Column<br>
Replace the missing values in Age with mean<br>
Remove the two rows of the remaining missing values

In [6]:
df.drop('Cabin',axis=1,inplace=True)
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.shape

(891, 11)

Check whether the missing values in the Age columns are replaced with mean or not

In [9]:
print(df['Age'][5])
print(df['Age'].isnull().sum())

29.69911764705882
0


Now remove the rows with missing values

In [10]:
df.dropna(inplace=True)
print(df.shape)
print(df.isnull().sum().sum())

(889, 11)
0


Assign the names columns to a new variable<br>
Remove the columns Name,Passenger Id, Ticket

In [11]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [12]:
names = df['Name']
df.drop(['Name','Ticket','PassengerId'],axis=1,inplace=True)
df.shape


(889, 8)

Check the categorical Columns

In [13]:
(df.dtypes == object).sum()

2

Caluculate the unique values in the categorical columns

In [14]:
print(df['Sex'].nunique())
print(df['Embarked'].nunique())

2
3


Convert the columns with two unique values using Label Binarizer

In [17]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit_transform(df['Sex'])

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
    

In [22]:
#lb.fit_transform(df['Sex']).reshape(-1)
df['Sex'] = lb.fit_transform(df['Sex']).flatten()
df['Sex'].dtype

dtype('int32')

Apply Label Encoder for the categorical columns 

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Embarked'] = le.fit_transform(df['Embarked'])
df['Embarked'][:3] 

0    2
1    0
2    2
Name: Embarked, dtype: int64

In [25]:
le.classes_

array(['C', 'Q', 'S'], dtype=object)

In [30]:
df.describe()

Survived      Pclass         Sex         Age       SibSp       Parch  \
count  889.000000  889.000000  889.000000  889.000000  889.000000  889.000000   
mean     0.382452    2.311586    0.649044   29.653446    0.524184    0.382452   
std      0.486260    0.834700    0.477538   12.968366    1.103705    0.806761   
min      0.000000    1.000000    0.000000    0.420000    0.000000    0.000000   
25%      0.000000    2.000000    0.000000   22.000000    0.000000    0.000000   
50%      0.000000    3.000000    1.000000   29.699118    0.000000    0.000000   
75%      1.000000    3.000000    1.000000   35.000000    1.000000    0.000000   
max      1.000000    3.000000    1.000000   80.000000    8.000000    6.000000   

             Fare    Embarked  
count  889.000000  889.000000  
mean    32.096681    1.535433  
std     49.697504    0.792088  
min      0.000000    0.000000  
25%      7.895800    1.000000  
50%     14.454200    2.000000  
75%     31.000000    2.000000  
max    512.329200    2.000000

Separate the output column

In [32]:
target = df.Survived
features = df.drop('Survived',axis=1)

Apply Minmax Scaler

In [34]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
features = pd.DataFrame(sc.fit_transform(features),
                        columns= features.columns)
features.describe()

Pclass         Sex         Age       SibSp       Parch        Fare  \
count  889.000000  889.000000  889.000000  889.000000  889.000000  889.000000   
mean     0.655793    0.649044    0.367347    0.065523    0.063742    0.062649   
std      0.417350    0.477538    0.162960    0.137963    0.134460    0.097003   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.500000    0.000000    0.271174    0.000000    0.000000    0.015412   
50%      1.000000    1.000000    0.367921    0.000000    0.000000    0.028213   
75%      1.000000    1.000000    0.434531    0.125000    0.000000    0.060508   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         Embarked  
count  889.000000  
mean     0.767717  
std      0.396044  
min      0.000000  
25%      0.500000  
50%      1.000000  
75%      1.000000  
max      1.000000

In [50]:
xtrain,xtest,ytrain,ytest = train_test_split(features,target,
                                             random_state=42)
xtrain.head()


Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
375     1.0  0.0  0.271174  0.000    0.0  0.014151       1.0
457     0.5  0.0  0.623021  0.000    0.0  0.020495       1.0
731     0.5  1.0  0.367921  0.000    0.0  0.000000       1.0
506     0.0  1.0  0.367921  0.000    0.0  0.051822       1.0
828     1.0  0.0  0.183212  0.125    0.0  0.028213       0.0

In [52]:
lr = LogisticRegression()
lr.fit(xtrain,ytrain)
ytest_pred  = lr.predict(xtest) 
ytrain_pred = lr.predict(xtrain)
print('----------Accuracy-------')
print('training',accuracy_score(ytrain_pred,ytrain))
print('testing',accuracy_score(ytest_pred,ytest))
print('----------f1score-------')
print('training',f1_score(ytrain_pred,ytrain))
print('testing',f1_score(ytest_pred,ytest))

----------Accuracy-------
training 0.8003003003003003
testing 0.7847533632286996
----------f1score-------
training 0.7302231237322514
testing 0.7142857142857143


In [53]:
knn = KNeighborsClassifier()
knn.fit(xtrain,ytrain)
ytest_pred  = knn.predict(xtest) 
ytrain_pred = knn.predict(xtrain)
print('----------Accuracy-------')
print('training',accuracy_score(ytrain_pred,ytrain))
print('testing',accuracy_score(ytest_pred,ytest))
print('----------f1score-------')
print('training',f1_score(ytrain_pred,ytrain))
print('testing',f1_score(ytest_pred,ytest))

----------Accuracy-------
training 0.8723723723723724
testing 0.7802690582959642
----------f1score-------
training 0.8268839103869654
testing 0.6993865030674846


In [54]:
help(KNeighborsClassifier)

Help on class KNeighborsClassifier in module sklearn.neighbors.classification:

class KNeighborsClassifier(sklearn.neighbors.base.NeighborsBase, sklearn.neighbors.base.KNeighborsMixin, sklearn.neighbors.base.SupervisedIntegerMixin, sklearn.base.ClassifierMixin)
 |  KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=1, **kwargs)
 |  
 |  Classifier implementing the k-nearest neighbors vote.
 |  
 |  Read more in the :ref:`User Guide <classification>`.
 |  
 |  Parameters
 |  ----------
 |  n_neighbors : int, optional (default = 5)
 |      Number of neighbors to use by default for :meth:`kneighbors` queries.
 |  
 |  weights : str or callable, optional (default = 'uniform')
 |      weight function used in prediction.  Possible values:
 |  
 |      - 'uniform' : uniform weights.  All points in each neighborhood
 |        are weighted equally.
 |      - 'distance' : weight points by the inverse of their

n_neighbors = [3,7,9,11,13]<br>
weights =['uniform','distance']<br>
accuracy<br>
knn(3,'uniform') <br> 
knn(3,'distance')<br>

--------
--------
knn(13,'distance')


In [55]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
scoring = make_scorer(accuracy_score)
params = {"n_neighbors":[3,7,9,11,13],
          "weights":['uniform','distance']}
grid = GridSearchCV(KNeighborsClassifier(),params,scoring)
grid.fit(xtrain,ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_neighbors': [3, 7, 9, 11, 13], 'weights': ['uniform', 'distance']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(accuracy_score), verbose=0)

In [56]:
grid.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [57]:
accuracy_score(grid.predict(xtest),ytest)

0.8026905829596412

In [59]:
from sklearn.model_selection import cross_val_score
cross_val_score(grid,features,target,cv=5)

array([0.76404494, 0.7752809 , 0.83146067, 0.79213483, 0.78531073])

In [60]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC(gamma="scale")
clf = GridSearchCV(svc, parameters, cv=5)
clf.fit(iris.data,iris.target)

TypeError: must be real number, not str

In [63]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [65]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [67]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [69]:
print(iris['DESCR'])

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  